using System;

namespace Sufficit.Asterisk.Manager.Action
{
    /// <summary>
    /// The AbsoluteTimeoutAction sets the absolute maximum amount of time permitted for a call on a given channel.
    /// This action establishes a hard timeout limit from the current time forward, canceling all previous absolute timeouts.
    /// </summary>
    /// <remarks>
    /// Asterisk Manager Action: AbsoluteTimeout
    /// Purpose: Set absolute timeout limit for active channels
    /// Privilege Required: call,all
    /// 
    /// Required Parameters:
    /// - Channel: The channel to set timeout on (Required)
    /// - Timeout: Timeout in seconds (Required)
    /// 
    /// Optional Parameters:
    /// - ActionID: Unique identifier for correlation (Optional)
    /// 
    /// Timeout Behavior:
    /// - Timeout starts counting from the current time
    /// - Does not include time the call has already been active
    /// - Setting a new timeout cancels all previous absolute timeouts
    /// - When timeout is reached, call is transferred to 'T' extension
    /// - Timeout value of 0 cancels any existing absolute timeout
    /// 
    /// Channel State Requirements:
    /// - Channel must be active and accessible
    /// - Works with any channel type (SIP, IAX2, DAHDI, etc.)
    /// - Channel must be in a state that allows timeout setting
    /// 
    /// Usage Scenarios:
    /// - Call duration limits for billing purposes
    /// - Emergency timeout for long-running calls
    /// - Conference call time limits
    /// - Customer service call duration control
    /// - Queue timeout management
    /// - IVR session timeout handling
    /// - Call center compliance requirements
    /// 
    /// Timeout Values:
    /// - 0: Cancel existing absolute timeout
    /// - 1-3600: Typical range (1 second to 1 hour)
    /// - Maximum depends on Asterisk configuration
    /// - Values over 7200 (2 hours) may be rejected
    /// 
    /// Dialplan Integration:
    /// When timeout is reached:
    /// - Call is transferred to 'T' extension in current context
    /// - Only calling party hears timeout handling
    /// - Called party is disconnected immediately
    /// - 'T' extension should handle timeout explanation
    /// 
    /// Example dialplan for timeout handling:
    /// ```
    /// exten => T,1,Playback(call-timeout)
    /// exten => T,n,Hangup()
    /// ```
    /// 
    /// Asterisk Versions:
    /// - Available since Asterisk 1.0
    /// - Consistent behavior across all versions
    /// - Enhanced error reporting in modern versions
    /// 
    /// Implementation Notes:
    /// This action corresponds to the AbsoluteTimeout() dialplan application.
    /// Implemented in main/manager.c in Asterisk source code.
    /// Uses Asterisk's scheduling subsystem for timeout tracking.
    /// 
    /// Security Considerations:
    /// - Can terminate active calls abruptly
    /// - Should be restricted to authorized users
    /// - Consider logging timeout actions for audit
    /// - Validate timeout values to prevent abuse
    /// 
    /// Error Conditions:
    /// - Channel not found or not accessible
    /// - Invalid timeout value (negative numbers)
    /// - Channel not in compatible state
    /// - Insufficient manager privileges
    /// 
    /// Monitoring and Events:
    /// - No specific events generated by this action
    /// - Timeout expiration triggers normal hangup events
    /// - Check CDR records for timeout-related hangups
    /// 
    /// Example Usage:
    /// <code>
    /// // Set 5-minute timeout on a channel
    /// var timeout = new AbsoluteTimeoutAction(
    ///     "SIP/1001-00000001", 
    ///     300
    /// );
    /// 
    /// // Cancel existing timeout
    /// var cancelTimeout = new AbsoluteTimeoutAction(
    ///     "SIP/1001-00000001", 
    ///     0
    /// );
    /// 
    /// // Set timeout with action ID for tracking
    /// var timeout = new AbsoluteTimeoutAction(
    ///     "SIP/1001-00000001", 
    ///     1800, 
    ///     "timeout_001"
    /// );
    /// </code>
    /// </remarks>
    /// <seealso cref="HangupAction"/>
    /// <seealso cref="RedirectAction"/>
    public class AbsoluteTimeoutAction : ManagerAction
    {
        /// <summary>
        /// Creates a new empty AbsoluteTimeoutAction.
        /// </summary>
        /// <remarks>
        /// This constructor creates an action with default values.
        /// You must set Channel and Timeout properties before using.
        /// Consider using the parameterized constructor for better initialization.
        /// </remarks>
        public AbsoluteTimeoutAction()
        {
            Channel = string.Empty;
            Timeout = 0;
        }

        /// <summary>
        /// Creates a new AbsoluteTimeoutAction with the given channel and timeout.
        /// </summary>
        /// <param name="channel">The name of the channel to set timeout on (Required)</param>
        /// <param name="timeout">The timeout in seconds or 0 to cancel existing timeout (Required)</param>
        /// <remarks>
        /// Channel Format Examples:
        /// - "SIP/1001-00000001" (SIP peer call)
        /// - "IAX2/provider/5551234567-00000001" (IAX trunk call)
        /// - "DAHDI/1-1" (DAHDI channel)
        /// - "Local/1001@from-internal-00000001;1" (Local channel leg)
        /// - "PJSIP/1001-00000001" (PJSIP endpoint)
        /// 
        /// Timeout Guidelines:
        /// - 0: Cancel existing absolute timeout
        /// - 30-1800: Common range (30 seconds to 30 minutes)
        /// - 3600: Maximum recommended (1 hour)
        /// - Negative values will cause errors
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown when channel is null</exception>
        /// <exception cref="ArgumentException">Thrown when channel is empty or timeout is negative</exception>
        public AbsoluteTimeoutAction(string channel, int timeout)
        {
            if (channel == null)
                throw new ArgumentNullException(nameof(channel));
            if (string.IsNullOrWhiteSpace(channel))
                throw new ArgumentException("Channel cannot be empty", nameof(channel));
            if (timeout < 0)
                throw new ArgumentException("Timeout cannot be negative", nameof(timeout));

            Channel = channel;
            Timeout = timeout;
        }

        /// <summary>
        /// Creates a new AbsoluteTimeoutAction with channel, timeout, and action ID.
        /// </summary>
        /// <param name="channel">The name of the channel to set timeout on (Required)</param>
        /// <param name="timeout">The timeout in seconds or 0 to cancel existing timeout (Required)</param>
        /// <param name="actionId">Unique identifier for this action (Optional)</param>
        /// <remarks>
        /// The action ID allows correlation of responses with this specific request.
        /// Useful for tracking the success/failure of timeout operations.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown when channel is null</exception>
        /// <exception cref="ArgumentException">Thrown when channel is empty or timeout is negative</exception>
        public AbsoluteTimeoutAction(string channel, int timeout, string actionId) : this(channel, timeout)
        {
            ActionId = actionId;
        }

        /// <summary>
        /// Gets the name of this action.
        /// </summary>
        /// <value>Always returns "AbsoluteTimeout"</value>
        public override string Action => "AbsoluteTimeout";

        /// <summary>
        /// Gets or sets the name of the channel to set timeout on.
        /// This property is required.
        /// </summary>
        /// <value>
        /// The channel name where the timeout will be applied.
        /// </value>
        /// <remarks>
        /// Channel Requirements:
        /// - Must be a valid, active channel
        /// - Channel must be accessible for timeout operations
        /// - Format depends on channel technology
        /// 
        /// Channel Examples:
        /// - "SIP/1001-00000001" (SIP peer call)
        /// - "IAX2/provider/5551234567-00000001" (IAX trunk call)
        /// - "DAHDI/1-1" (DAHDI channel)
        /// - "Local/1001@from-internal-00000001;1" (Local channel leg)
        /// - "PJSIP/1001-00000001" (PJSIP endpoint)
        /// - "Bridge/xyz-1" (Bridge channel in modern Asterisk)
        /// 
        /// Channel State Compatibility:
        /// - "Up": Answered calls (most common)
        /// - "Ring": Ringing outbound calls
        /// - "Ringing": Ringing inbound calls
        /// - Other states may work depending on channel type
        /// 
        /// Channel Technology Support:
        /// - SIP/PJSIP: Full support for all timeout operations
        /// - IAX2: Full support with proper IAX2 configuration
        /// - DAHDI: Supported for digital and analog channels
        /// - Local: Supported, timeout applies to specified leg
        /// - Bridge: Modern Asterisk bridge channel support
        /// 
        /// The channel must exist and be in an appropriate state for timeout setting.
        /// Use Status action or channel events to verify channel existence and state.
        /// </remarks>
        public string Channel { get; set; }

        /// <summary>
        /// Gets or sets the timeout (in seconds) to set.
        /// This property is required.
        /// </summary>
        /// <value>
        /// The timeout value in seconds, or 0 to cancel existing timeout.
        /// </value>
        /// <remarks>
        /// Timeout Value Guidelines:
        /// 
        /// Special Values:
        /// - 0: Cancel any existing absolute timeout on the channel
        /// 
        /// Common Ranges:
        /// - 30-120: Short calls (2-minute limit)
        /// - 300-900: Standard calls (5-15 minute limits)
        /// - 1800-3600: Long calls (30-60 minute limits)
        /// - 7200+: Extended calls (2+ hours, use carefully)
        /// 
        /// Use Case Examples:
        /// - 30: Quick IVR timeout
        /// - 180: Customer service initial response
        /// - 600: Standard support call limit
        /// - 1800: Conference call timeout
        /// - 3600: Maximum billable hour limit
        /// 
        /// Technical Limits:
        /// - Minimum: 0 (cancel timeout)
        /// - Maximum: Depends on Asterisk configuration
        /// - Typical maximum: 86400 (24 hours)
        /// - Recommended maximum: 7200 (2 hours)
        /// 
        /// Timeout Precision:
        /// - Resolution: 1 second
        /// - Accuracy: ±1 second depending on system load
        /// - Timer starts immediately when action is processed
        /// - Does not account for network or processing delays
        /// 
        /// Billing Considerations:
        /// - Timeout should align with billing increments
        /// - Consider grace periods for customer experience
        /// - Log timeout events for billing accuracy
        /// - Coordinate with CDR timeout handling
        /// 
        /// Performance Impact:
        /// - Very low overhead per timeout
        /// - Asterisk handles thousands of concurrent timeouts
        /// - Memory usage increases slightly per active timeout
        /// - No significant CPU impact under normal loads
        /// 
        /// Error Conditions:
        /// - Negative values: Will be rejected by Asterisk
        /// - Very large values: May be capped by system limits
        /// - Zero on non-timeout channel: Safe operation (no effect)
        /// </remarks>
        public int Timeout { get; set; }
    }
}